name: Spork-S5ThemePixel
version: 0.01
abstract: Pixel Theme for Spork::S5
author: Florian Merges <fmerges@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Spork::S5: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
